version: '3.8'

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      -  NODE_ENV=development
      -  MONGO_URI=mongodb://admin:password@mongo:27017/?authSource=admin
      -  REDIS_URI=redis://redis:6379
      -  SESSION_SECRET=secret
    command: npm run dev